AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:

  AWSWhatsNewPublisher:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: rss_parser.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sns:Publish'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:sns:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':'
                    - Ref: 'AWSWhatsNewTopic'
            - Effect: Allow
              Action:
                - 'dynamodb:PutItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:Query'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/'
                    - Ref: 'AWSWhatsNewTable'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Tags:
        CostCenter: AWSWhatsNew
        auto-stop: 'no'
        auto-delete: 'no'
        ResourceGroup: AWSWhatsNew

    AWSWhatsNewTable:
     Type: AWS::Serverless::SimpleTable
     Properties:
       TableName: whatsnew_announces
       PrimaryKey:
         Name: id
         Type: String
       ProvisionedThroughput:
         ReadCapacityUnits: 1
         WriteCapacityUnits: 1

    AWSWhatsNewTopic:
      Type: 'AWS::SNS::Topic'
      TopicName: aws_whatsnew
